### ISSUE TITLE
extending this library

### ISSUE THREAD

**Issue by bryab** [cjab/libeq#1]
hello friend, I have been extending this project for a little game thing I'm working on.

I am however not really a Rust guy by any means, and I am using this as an opportunity to learn Rust a bit better.  I have a few head-scratchers at the moment as to how to add some features to your library in the Rust-idiomatic way.  If you feel like chatting about it, please send me a message.

Otherwise, ignore this and look out for some random stuff getting added to my fork as I continue my meanderings...

**Comment by cjab** [comment]
Hey there!

I'm not the most experienced Rust programmer in the world but maybe I can help :D. What sorts of features are you trying to add? 

Also, I have some updates to the wld file parser I've been meaning to push up for a while. I'll need to clean them up a bit but maybe I'll get a chance this weekend :D. They're mostly some updates to fields that were previously unknown on some of the fragment types.

**Comment by bryab** [comment]
Oh, that would be wonderful.  I have been adding new fragments, as I intend to use this library to load more than just the zone geometry, but also the lights and objects.  This gets quite complicated!

Well my main issue at the moment are the cases where fragment references can point to different types of fragments.  The FragmentRef wrapper is designed for when the exact type of fragment is known; not sure the right approach dealing with it when it is not.  At the moment I am just wrapping an i32 and then manually "casting" it to the appropriate fragment type when I know what type it is; but this is less than elegant.

I will likely push some changes to my fork in the next week or two that add quite a number of new fragment types.

**Comment by cjab** [comment]
Oh man, yeah, I cycled through several designs trying to get around the weirdness with
the heterogenous array of fragment types you end up with here. It's definitely not immediately obvious coming from other languages how to design this sort of thing in
Rust 😆.

Unfortunately, I haven't found a great way to do it without providing the target Type. The thing that probably looks the most promising at first is a `Vec` of trait objects. But you're not able to get the original object type back which leaves you kind of stuck :\.

The one avenue that I haven't really explored yet is the `Any` type. I'm not entirely sure it would work but the impression I get is that it may be able to do something like this?

That said, I found this video to help a ton in understanding a lot of this:

https://www.youtube.com/watch?v=xcygqF5LVmM&t=2834s

You've got me thinking about this problem again 😆.

**Comment by bryab** [comment]
Hey there.  If you have any opinions on how best to handle bitflags, I'd like to hear them.  Unfortunately when all the bit flags are not known, you must use this unsafe function to parse the flags.  Maybe there's a safe way to make this work (maybe without the bitflags crate)

https://github.com/bryab/eq_wld/blob/7f98d3b27b5960287637cd25262626149614c286/src/parser/fragments.rs#L1130

**Comment by cjab** [comment]
Hrmmm, good question. The first thing that comes to mind is to create a new type wrapping a u32. And then implement methods on it to check for the status of the flags. That way you can sidestep that nasty unsafe (and the bitflags crate) :D.

Something like this:

```rust
struct ModelReferenceFragmentFlags(u32)

impl ModelReferenceFragmentFlags {
    pub fn no_fragments(&self) -> bool {
        self.0 & 0b01000000 == 0b01000000
    }

    pub fn has_params_1(&self) -> bool {
        self.0 & 0b00000001 == 0b00000001
    }
}

let flags = ModelReferenceFragmentFlags(0x01);
let result = flags.no_fragments() && flags.has_params_1();
```

Disclaimer: I have not executed this 😆.

**Comment by cjab** [comment]
I just opened up a PR with most of the parser changes I had laying around here. It was a lot more than I remembered! I know you've made some changes too so I wanted to open a PR to make it a bit easier to see. I've been kind of off on my own on this for quite a while 😛. I'll try to be a bit better of a steward of this repo in the future 😄 .

https://github.com/cjab/eq_wld/pull/3

I think the next thing I want to get up here is the TUI tool I've been using to view fragments.

**Comment by cjab** [comment]
I just managed to get the tool pushed up. 

https://github.com/cjab/eq_wld/pull/4/files

It's pretty rough but still has been helpful for me.

**Comment by bryab** [comment]
Awesome, thanks for this!

**Comment by bryab** [comment]
I've successfully merged in your changes on my end, and will hopefully make a small-ish PR in a week or so, after stripping things down a bit more...
