### ISSUE TITLE
qeynos_obj.s3d fails to load

### ISSUE THREAD

**Issue by bryab** [cjab/libeq#9]
It seems many of the `_obj` files fail at this line (I saw it on `eastkarana_obj.s3d` too)

```
ERROR: [RUST] file 'D:\dev\godot\eq_wld\src\parser\mod.rs' at line 295: panic occurred: "called `Result::unwrap()` on an `Err` value: Error(([], Eof))"
```

https://github.com/cjab/eq_wld/blob/e66e12230a4ceb64c8428c6e48a13d5a3f27aeff/src/parser/mod.rs#L295

**Comment by bryab** [comment]
I will look at this myself when I have time, but wanted to put it up here.

**Comment by bryab** [comment]
"entries2" must not actually work as described in the WLD ref.  Will need to figure out how you extracted those frag fixtures, and make a new one from a wld that actually has "entries2" in this frag

**Comment by cjab** [comment]
I just pushed some changes to the `wld-cli` tool. There are now two subcommands `wld-cli explore WLD_FILE` for the tui and `wld-cli extract WLD_FILE DESTINATION` to extract raw fragment bodies (.frags). I added a little bit more documentation in the README around it too!
